# Generated by Django 6.0 on 2025-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(max_length=255)),
                ('matn', models.CharField(max_length=255)),
                ('muallif', models.CharField(max_length=255)),
                ('yaratilgan_sana', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
